- name: configure backend server
  hosts: backend
  become: yes
  vars:
    login_host: db.santhosh78s.online
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: #only works for radhat family
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user: 
      name: expense
  
  - name: create app directory
    ansible.builtin.file: 
      path: /app
      state: directory
  # - name: imstall nodejs
  #   ansible.builtin.dnf: dnf install nodejs -y
   