- name: configure backend server
  hosts: localhost
  become: yes
  vars:
    login_host: db.santhosh78s.online
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user: 
      name: expense

  # - name: imstall nodejs
  #   ansible.builtin.dnf: dnf install nodejs -y
   